---
title: "South Africa - COVID-19 profile"
author: "Anshu Uppal"
date: "12/27/2021"
output: pdf_document
params:
        continent: "Africa"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## COVID-19 profile in South Africa

Profile includes weekly deaths (all-cause), daily cases of COVID-19, and the different Alert Level periods set by the government.

```{r include=FALSE, message=FALSE, warning=FALSE}
# for the first time, use install.packages() to install each of the below packages, then you can run the lines below
library(tidyverse)
library(lubridate)
library(ggrepel)
library(readxl)
library(httr)
library(plotly)
library(scales)

# Deaths data from https://www.samrc.ac.za/reports/report-weekly-deaths-south-africa
# This url should be replaced to get the latest data from the website on deaths
url1 <- 'https://www.samrc.ac.za/sites/default/files/files/2021-12-22/Estimated%20deaths%20for%20SA%2020%20Dec%202021%20with%20adj2.xlsx'
GET(url1, write_disk(tf <- tempfile(fileext = ".xlsx")))
total_deaths <- tibble(read_xlsx(tf, sheet = 2, skip = 1)) %>% 
        select(-...1) %>% rename(Date = ...2, Deaths = `ALL CAUSE`) %>% drop_na(Date) %>%
        mutate(Date = ymd(Date),
               Year = as.character(year(Date)),
               Week = as.numeric(epiweek(Date)),
               Deaths = round(Deaths)) %>%
        select(-c(NATURAL, UNNATURAL)) %>% # no need to keep these as we want "All cause"
        relocate(c(Year, Deaths), .after = Week) %>%
        filter(Date > ymd("2020-02-28"))

mdate <- ymd(max(total_deaths$Date)) # generate a value for the latest date in the deaths data

# Data comes from Our World in Data (very comprehensive dataset - no need to update this link): https://ourworldindata.org/coronavirus/country/south-africa
url2 <- "https://covid.ourworldindata.org/data/owid-covid-data.csv"
GET(url2, write_disk(tf2 <- tempfile(fileext = ".csv")))
cases <- read_csv(tf2) %>%
        # read_csv("owid-covid-data.csv") %>%
        mutate(Date = ymd(date),
               Week = epiweek(Date)) %>%
        # select(Date, Week, location, new_cases, new_cases_smoothed) %>%
        filter(location == "South Africa"
               # , Date <= mdate # only if we want the cases date limits to be the same as the deaths date limits
        )

# Alert Levels dates manually compiled from https://www.gov.za/covid-19/about/about-alert-system
alert <- read_csv("Alert Levels.csv") %>% 
        mutate(
                Alert_Level = as.character(Alert_Level),
                Start_Date = dmy(Start_Date),
                # Start_Date = as.POSIXct(Start_Date),
                End_Date = dmy(End_Date),
                # End_Date = as.POSIXct(End_Date),
                End_Date = if_else(is.na(End_Date), max(cases$Date), End_Date)
        )
```

```{r echo=FALSE, warning=FALSE}
# Graph showing weekly deaths and daily cases (smoothed)
ggplot()+
        geom_rect(data = alert, aes(xmin = Start_Date, xmax = End_Date, # alert level shadings
                                    ymin = -Inf, 
                                    ymax = Inf,
                                    # ymin = min(total_deaths$Deaths)-100, 
                                    # ymax = max(total_deaths$Deaths)+100,
                                    fill = Alert_Level
        ), # geom_rect plotted first so that it goes begind the trend lines
        alpha = 0.6)+
        geom_path(data = total_deaths, aes(x = Date, y = Deaths, color = "blue"), size = 1)+ # not sure why colors get inverted for cases and deaths
        geom_point(data = total_deaths, aes(x = Date, y = Deaths), color = "red", size = 1)+
        geom_path(data = cases, aes(x=Date, y = new_cases_smoothed, color = "red"), size = 1)+
        scale_color_manual(labels = c("Weekly deaths", "Daily cases"), values = c("red", "blue"))+
        scale_fill_manual('Alert Level', # manually choose the colors for the alert level shades
                          values = c("#D4E157", "#FFEE58", 
                                     "#FFCA28", "#F57C00", "#B71C1C"))+
        labs(title = "Weekly deaths (all-cause) and daily COVID-19 cases (7-day smoothed)", color = "")+
        theme_bw()+
        scale_x_date(date_breaks = "2 months", date_labels = "%b-%Y", minor_breaks = NULL)+
        scale_y_continuous(labels = scales::comma, minor_breaks = NULL)+
        theme(axis.title.y = element_blank(),
              axis.title.x = element_blank(),
              legend.key=element_blank()
              # , legend.position = "none"
              , legend.position = c(0.09,0.72) # can play around with these to get a good legend positioning
              , legend.background = element_rect(fill = NA, size = 0)
              , axis.text.x = element_text(angle = 30 , vjust = 0.7, size = 13)
              , panel.grid.major.x = element_blank()
              , panel.grid.minor.x = element_blank()
        )+
        guides(fill = guide_legend(override.aes = list(linetype = 0))) # get rid of lines in legend squares
```

```{r include=FALSE, message=FALSE, warning=FALSE, echo=FALSE}
cases2 <- read_csv(tf2) %>%
        # read_csv("owid-covid-data.csv") %>%
        mutate(Date = ymd(date),
               Week = epiweek(Date)) %>%
        # select(Date, Week, location, new_cases, new_cases_smoothed) %>%
        filter(continent == params$continent
               # , Date <= mdate # only if we want the cases date limits to be the same as the deaths date limits
        )
```

```{r echo=FALSE, warning=FALSE, message=FALSE,fig.cap="**Not for paper** -> for regional comparison"}
# Graph showing weekly deaths and daily cases (smoothed)
ggplot(data = cases2)+
        geom_path(aes(x=Date, y = new_cases_smoothed), size = 1)+
        labs(title = "Daily COVID-19 cases (7-day smoothed)")+
        theme_bw()+
        scale_x_date(date_breaks = "6 months", date_labels = "%b-%Y", minor_breaks = NULL)+
        scale_y_continuous(labels = scales::comma, minor_breaks = NULL)+
        theme(axis.title.y = element_blank(),
              axis.title.x = element_blank(),
              axis.text.x = element_text(angle = 30 , vjust = 0.7, size = 13)
              , panel.grid.major.x = element_blank()
              , panel.grid.minor.x = element_blank()
        )+
        facet_wrap(.~location)
```

```{r include=FALSE, message=FALSE, warning=FALSE, echo=FALSE}
library(plotly)
library(tidyverse)
library(lubridate)
library(ggrepel)

gg_color_hue <- function(n) {
        hues = seq(15, 375, length = n + 1)
        hcl(h = hues, l = 65, c = 100)[1:n]
}

# data from http://ghdx.healthdata.org/gbd-results-tool
d2 <- read_csv("IHME-GBD_2019_DATA-ed657013-1.csv") %>% 
        rename(Country = location_name, Year = year) %>%
        filter(metric_name == "Number",
               # measure_name != "Prevalence",
               Year < 2018
               ) %>%
        mutate(measure_name = if_else(measure_name == "Prevalence", "Prevalence (x10)", measure_name)
               , tprev = paste(cause_name, measure_name)
               , val2 = if_else(tprev == "HIV/AIDS Prevalence (x10)", val/10, val)
               # , val2 = if_else(cause_name == "Tuberculosis", (val2)*3, val2)
               , label = if_else(Year == max(Year), measure_name, NA_character_)
               , label = if_else(Year == c(2015, 2016), "", label)
               , label = if_else(tprev == "Tuberculosis Incidence" & Year == c(2015, 2016), 
                                 NA_character_, label)
               , label = if_else(tprev == "HIV/AIDS Deaths" & Year == c(2015,2016), 
                                 NA_character_, label)
               , label2 = if_else(Year == max(Year), tprev, NA_character_)
               , label2 = if_else(Year == c(2015, 2016), "", label2)
               ) %>%
        filter(tprev != "Tuberculosis Prevalence (x10)"
               # , cause_name == "Tuberculosis"
               # , tprev != "Tuberculosis Deaths"
               ) %>%
        arrange(Year)

# Population data from World Bank: https://datatopics.worldbank.org/world-development-indicators/themes/people.html
d3 <- read_csv("population_world bank.csv", skip = 4) 
d3 <- d3 %>% rename(Country = `Country Name`) %>%
        filter(Country == "South Africa") %>%
        select(-c(1:4, ...66)) %>%
        pivot_longer(cols = `1960`:`2020`, names_to = "Year", values_to = "Population") %>%
        filter(Year > 1989, Year < 2018)
d4 <- merge(d2, d3) %>% mutate(rate = (val2/Population)*100000
                               # , rate = if_else(cause_name == "Tuberculosis", (rate-330)*15, rate)
)
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
## Main plot
d4 %>% 
        # filter(tprev != "Tuberculosis Deaths") %>%
        ggplot(aes(x = Year, y = rate, group = tprev, colour = cause_name))+
        geom_path(aes(linetype = measure_name), show.legend = FALSE)+
        geom_point(aes(shape = measure_name), show.legend = FALSE)+
        labs(title = "HIV/AIDS and Tuberculosis Estimates in South Africa, 1990-2017",
             y = "Estimates (per 100,000 population)")+
        scale_y_continuous(labels = scales::comma, n.breaks = 8
                           , sec.axis = dup_axis(breaks = seq(0,1400,200))
                           # , sec.axis = sec_axis( ~ . /15 + 330
                           #                        , breaks = c(330, 350, 375, 400, 425)
                           #                        , name = "Estimate for Tuberculosis (per 100,000 population)")
                           )+
        scale_x_continuous(n.breaks = 6, limits = c(1990, 2017))+
        geom_text_repel(aes(label = label2, color = cause_name, size = 12)
                        # , nudge_x = -1
                        # , nudge_y = 30
                        # , force = 4
                        # , point.padding = 2
                        , na.rm = TRUE
                        , show.legend = FALSE
        )+
        theme_bw()+
        # facet_wrap(.~cause_name, scales = "free")+
        # guides(linetype = "none")
        # theme(axis.title.y = element_blank())+
        theme(panel.grid.minor.x = element_blank()
              , panel.grid.major.x = element_blank()
              , panel.grid.major = element_blank()
              , panel.grid.minor = element_blank()
              # , legend.title = element_blank()
              # , legend.position = c(0.75, 0.94)
              # , legend.background = element_rect(fill = NA)
              # , legend.key = element_rect(colour = NA, fill = NA)
              ,legend.position = "none"
              , axis.text.x = element_text(size = 12)
              , axis.text.y = element_text(size = 12)
              # , axis.text.y.left = element_text(color = "#F8766D")
              # , axis.title.y.left = element_text(color = "#F8766D")
              # , axis.text.y.right = element_text(color = "#00BFC4")
              # , axis.title.y.right = element_text(color = "#00BFC4")
        )
```